# -*- coding: utf-8 -*-
"""AML_Assessment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QyGagJXYif2xsjN8q-OyFm1RpChWsLSH

# Notebook Index

- [Imports, Data Loading, & Description](#scrollTo=inNgkZcjjfOH)
- [Visualize Data](#scrollTo=DPRWc8ha6sXj)
- [Visualize Missing Values](#scrollTo=b5XLbYg06gmT)
- [Fill Missing Values & Deal with Outliers](#scrollTo=EenFUaET7PIi)
  - [Missing Values For year_of_registration](#scrollTo=ChCbm3mt7R2H)
  - [Missing Values For mileage](#scrollTo=m5nZhV8S7fiW)
  - [Missing Values For standard_colour](#scrollTo=4qsDjftl7kdl)
  - [Missing Values For body_type](#scrollTo=lNs_cUTB7r_x)
  - [Missing Values For fuel_type](#scrollTo=f4M6dsKt7xub)
- [Feature Engineering & Preprocessing](#scrollTo=bNNtT91N8E8P)
- [Automated Feature Selection (AFS)](#scrollTo=2jkD7TgRYe1L)
  - [Without FS](#scrollTo=xUPGKOzzorgP)
  - [Sequential Feature Selection (SFS) (Forward/Backward)](#scrollTo=4vT_nJUK2N5r)
  - [With Best-k](#scrollTo=28mn7OB8n9lw)
  - [Recursive Feature Elimination (RFE)](#scrollTo=zBsmT-2EYmh7)
- [Gradient Boosting Regressor & Random Forest Regressor & Linear Regressor](#scrollTo=dY8jkbqGCCKX)
- [Model Fitting](#scrollTo=kHCcXRbhGuNy)
- [Model Ensembling (Voting, Boosting, Stacking)](#scrollTo=y-DSY29NFm42)
- [Ensembling](#scrollTo=WZfUSPprFzXv)
- [Permutation Importance](#scrollTo=Elq3xG7bMe1a)
- [SHAP Explainer and Local Explanations](#scrollTo=4qQKje9tRfdn)
- [Visualising Predictions as A Function of A Feature](#scrollTo=G5jMbql92fZn)
  - [Partial Dependency Plot (PDP)](#scrollTo=LLeE7RJNJSXf)
- [Dimensionality Reduction (Linear)](#scrollTo=MlAz12KoG_4o)
  - [2 components (Elbow point)](#scrollTo=wFYXEnn_P_t2)
- [Nonlinear Dimensionality Reduction (MDS)](#scrollTo=4t-XldhPQMiI)
  - [Isomap](#scrollTo=zF5rhjd-TCnJ)
  - [t-SNE](#scrollTo=TywrBw45Tozo)
  - [Side-by-side comparison](#scrollTo=AMVFfPv8uY1M)
- [Clustering (K-mean)](#scrollTo=MPn4KlfmAhE9)
  - [K-means clustering using 'sklearn library'](#scrollTo=MjgZM5SFjFyl)
  - [K-mean Visualization](#scrollTo=LbdxKmM_i8qt)
  - [Optimal k (Elbow method)](#scrollTo=wA7WeP-QmE30)
  - [Elbow method visualization](#scrollTo=Dq-_-mm-m3TY)
  - [Knee locater](#scrollTo=eiCGX6IUnUCO)
- [Generalized Linear Models](#scrollTo=QSeTI4mNi3BX)
  - [Polynomial Regression](#scrollTo=SyTwRQdtjYBe)
  - [Visualization](#scrollTo=PShhJnCNtEdX)

# Part 1

## Imports, Data Loading, & Description
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import pandas as pd
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
import warnings
import shap
!pip install kneed
from kneed import KneeLocator
from google.colab import drive
!pip install category_encoders
sns.set({ "figure.figsize": (6, 4) }, style='ticks', color_codes=True, font_scale=0.8)
# %config InlineBackend.figure_format = 'retina'
warnings.filterwarnings('ignore')
shap.initjs()
drive.mount('/content/drive')

from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor, VotingRegressor
from sklearn.model_selection import train_test_split, cross_val_score, cross_validate
from sklearn.inspection import permutation_importance, PartialDependenceDisplay
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.linear_model import LinearRegression
from sklearn.compose import TransformedTargetRegressor, ColumnTransformer
from sklearn.manifold import MDS, Isomap, TSNE
from sklearn.decomposition import PCA
from category_encoders import TargetEncoder
from sklearn.pipeline import Pipeline
from sklearn.cluster import KMeans, DBSCAN
from sklearn import set_config
set_config(transform_output='pandas')

# Read the CSV file into a DataFrame named AT
AT = pd.read_csv('/content/drive/MyDrive/adverts.csv')

# Display the first few rows of the DataFrame
display(AT.head())

AT_copy = AT.copy()  # create a deep copy of AT

AT_demo = AT.copy()

# Get the number of rows and columns
num_rows, num_cols = AT.shape

print(f"Number of rows: {num_rows}")
print(f"Number of columns: {num_cols}")

AT.describe().T

"""## Visualize Data"""

# Price distribution
sns.histplot(AT['price'], kde=True)
plt.title("Original Price Distribution")
plt.show()

print("Original Skew:", AT['price'].skew())

"""Since data is skewed lets use log transform on AT_demo and plot."""

AT_demo['price_log'] = np.log1p(AT['price'])

sns.histplot(AT_demo['price_log'], kde=True)
plt.title("Log-Transformed Price Distribution")
plt.show()

print("Transformed Skew:", AT_demo['price_log'].skew())

# Mileage distribution
plt.figure(figsize=(10,5))
sns.histplot(AT['mileage'], bins=100, kde=True)
plt.title('Mileage Distribution')
plt.xlim(0, 200000)
plt.show()

# Price by vehicle_condition
plt.figure(figsize=(6,4))
sns.boxplot(x='vehicle_condition', y='price', data=AT)
plt.ylim(0, 200000)
plt.title('Price vs Vehicle Condition')
plt.show()

# Price by fuel_type
plt.figure(figsize=(8,5))
sns.boxplot(x='body_type', y='price', data=AT)
plt.ylim(0, 200000)
plt.xticks(rotation=45)
plt.title('Price vs Fuel Type')
plt.show()

# Top 20 models by median price
top_models = AT.groupby('standard_model')['price'].median().sort_values(ascending=False).head(20)
plt.figure(figsize=(12,5))
sns.barplot(x=top_models.index, y=top_models.values)
plt.xticks(rotation=90)
plt.title('Top 20 Models by Median Price')
plt.show()

sns.scatterplot(x='mileage', y='price',hue='vehicle_condition', data=AT, alpha=0.5)
plt.xlim(0, 200000)
plt.ylim(0, 200000)
plt.title('Price vs Mileage')
plt.show()

sns.scatterplot(x='mileage', y='price',hue='fuel_type', data=AT, alpha=0.5, palette='Paired')
plt.xlim(0, 200000)
plt.ylim(0, 200000)
plt.title('Price vs Mileage')
plt.show()

sns.scatterplot(x='year_of_registration', y='price', data=AT, alpha=0.3)
plt.title('Price vs year_of_registration')
plt.show()

plt.figure(figsize=(10, 8))
sns.heatmap(AT_demo[['mileage', 'year_of_registration', 'price_log']].corr(),square=True, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Heatmap of Numerical Features')
plt.show()

"""## Visualize Missing Values"""

# Check for null values
print("Null values per column:")
display(AT.isnull().sum())

AT.isnull().sum().plot(kind='bar')
plt.title('Missing Values Bar Chart')
plt.ylabel('Missing Values Count')
plt.show()

"""## Fill Missing Values & Deal with Outliers

### Missing Values For year_of_registration
Group by using standard model to fill missing values
"""

AT_copy['year_of_registration'] = AT_copy['year_of_registration'].fillna(
    AT_copy.groupby('standard_model')['year_of_registration'].transform('median')
)

AT_copy['year_of_registration'] = AT_copy['year_of_registration'].fillna(
    AT_copy.groupby('standard_make')['year_of_registration'].transform('median')
)

AT_copy['year_of_registration'] = AT_copy['year_of_registration'].fillna(
    AT['year_of_registration'].median()
)

temp_years_imputation = (
    AT_copy.groupby(['standard_model','standard_colour','standard_make','body_type'])['year_of_registration']
    .transform('median')
)

mask = AT_copy['year_of_registration'] < 1903
AT_copy.loc[mask, 'year_of_registration'] = temp_years_imputation[mask]

AT_copy['year_of_registration'].min()

"""### Missing Values For mileage"""

AT_copy['mileage'] = AT_copy['mileage'].fillna(
    AT_copy.groupby(['standard_model', 'standard_make'])['mileage']
    .transform('median')
)

"""### Missing Values For standard_colour"""

AT_copy['standard_colour'] = AT_copy['standard_colour'].fillna(
    AT_copy.groupby(['standard_model', 'standard_make'])['standard_colour']
    .transform(lambda x: x.mode()[0] if not x.mode().empty else np.nan)
)

global_mode = AT_copy['standard_colour'].mode()[0]
AT_copy['standard_colour'] = AT_copy['standard_colour'].fillna(
    AT_copy.groupby('standard_make')['standard_colour']
    .transform(lambda x: x.mode()[0] if not x.mode().empty else global_mode)
)

"""### Missing Values For body_type"""

AT_copy['body_type'] = AT_copy['body_type'].fillna(
    AT_copy.groupby(['standard_model', 'standard_make'])['body_type']
    .transform(lambda x: x.mode()[0] if not x.mode().empty else np.nan)
)

global_mode = AT_copy['body_type'].mode()[0]
AT_copy['body_type'] = AT_copy['body_type'].fillna(
    AT_copy.groupby('standard_make')['body_type']
    .transform(lambda x: x.mode()[0] if not x.mode().empty else global_mode)
)

"""### Missing Values For fuel_type"""

AT_copy['fuel_type'] = AT_copy['fuel_type'].fillna(
    AT_copy.groupby(['standard_model', 'standard_make'])['fuel_type']
    .transform(lambda x: x.mode()[0] if not x.mode().empty else np.nan)
)

global_mode = AT_copy['fuel_type'].mode()[0]
AT_copy['fuel_type'] = AT_copy['fuel_type'].fillna(
    AT_copy.groupby('standard_make')['fuel_type']
    .transform(lambda x: x.mode()[0] if not x.mode().empty else global_mode)
)

AT_copy.isnull().sum()

# Identify outliers using the IQR method for Price and Mileage
def find_outliers_iqr(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return lower_bound, upper_bound

price_lower, price_upper = find_outliers_iqr(AT_copy, 'price')
mileage_lower, mileage_upper = find_outliers_iqr(AT_copy, 'mileage')
# Filter the dataset
AT_copy_1 = AT_copy[
    (AT_copy['price'] >= price_lower) & (AT_copy['price'] <= price_upper) &
    (AT_copy['mileage'] >= mileage_lower) & (AT_copy['mileage'] <= mileage_upper)]

print(f"Rows before: {len(AT_copy)}")
print(f"Rows after removing outliers: {len(AT_copy_1)}")
print(f"Percentage removed: {(1 - len(AT_copy_1)/len(AT_copy))*100:.2f}%")

AT_copy_1['vehicle_age'] = 2024 - AT_copy_1['year_of_registration']
AT_copy_1['mileage_per_year'] = AT_copy_1['mileage'] / (AT_copy_1['vehicle_age'] + 1)

display(AT_copy.tail())

"""## Feature Engineering & Preprocessing"""

target = 'price'
low_card_cat_feat = ['body_type','fuel_type']#
binary_cat_feat = ['vehicle_condition']#
high_card_cat_feat = ['standard_model','standard_make','standard_colour']#
num_feat = ['mileage_per_year','vehicle_age']

X = AT_copy_1[low_card_cat_feat + high_card_cat_feat + num_feat + binary_cat_feat]
y = AT_copy_1[target]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# y_train_log = np.log1p(y_train)
# y_test_log  = np.log1p(y_test)

preprocessor = ColumnTransformer(
    transformers=[
        ('scaler', StandardScaler(), num_feat),
        ('onehot', OneHotEncoder(sparse_output=False, handle_unknown='infrequent_if_exist',  # groups rare categories
        drop='if_binary'), low_card_cat_feat),
        ('tar_enc', TargetEncoder(smoothing=10), high_card_cat_feat),
        ('ordinal_enc', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), binary_cat_feat),
    ],
    remainder='passthrough',
    verbose_feature_names_out=False)

"""## Automated Feature Selection (AFS)

### Without FS
"""

regr_noFS = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("regr", TransformedTargetRegressor(
            regressor=GradientBoostingRegressor(n_estimators=100, max_depth=5, random_state=42),
            func=np.log1p, inverse_func=np.expm1))
    ])

print("Fitting GradientBoostingRegressor on full training set...")
regr_noFS.fit(X_train, y_train)

print("Test R2:", regr_noFS.score(X_test, y_test))
print("Train R2:", regr_noFS.score(X_train, y_train))

print("Test MAE:", mean_absolute_error(y_test, regr_noFS.predict(X_test)),"Train MAE:", mean_absolute_error(y_train, regr_noFS.predict(X_train)))

eval_results = cross_validate(
    regr_noFS, X_train, y_train, cv=5,
    scoring='neg_mean_absolute_error',
    return_train_score=True)
((-eval_results['test_score'].mean(), eval_results['test_score'].std(),
    -eval_results['train_score'].mean(), eval_results['train_score'].std()))

regr_noFS['preprocessor'].get_feature_names_out()

len(regr_noFS['preprocessor'].get_feature_names_out())

"""### Sequential Feature Selection (SFS) (Forward/Backward)

dropped due to computational efficiency

### With Best-k
"""

regr_bestk = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("featsel", SelectKBest(f_regression, k=10)),
        ("regr", TransformedTargetRegressor(
            regressor=GradientBoostingRegressor(n_estimators=100, max_depth=5, random_state=42),
            func=np.log1p, inverse_func=np.expm1))
    ])

regr_bestk.fit(X_train, y_train)

preds_test = regr_bestk.predict(X_test)
preds_train = regr_bestk.predict(X_train)

print("Test MAE:", mean_absolute_error(y_test, preds_test))
print("Train MAE:", mean_absolute_error(y_train, preds_train))

feature_names = regr_bestk.named_steps["preprocessor"].get_feature_names_out()
selected_features = regr_bestk.named_steps["featsel"].get_feature_names_out(feature_names)
len(selected_features)

print(selected_features)

print("Train R2:", regr_bestk.score(X_train, y_train))
print("Test R2:", regr_bestk.score(X_test, y_test))

"""###Recursive Feature Elimination (RFE)"""

# from sklearn.feature_selection import RFECV

# regr_rfe = Pipeline(
#     steps=[
#         ("preprocessor", preprocessor),
#         ("featsel", RFECV(base_regressor, step=2, cv=3, n_jobs=-1)),
#         ("regr", TransformedTargetRegressor(
#             regressor=GradientBoostingRegressor(max_depth=5, random_state=42),
#             func=np.log1p, inverse_func=np.expm1
#         ))
#     ]
# )
# regr_rfe.fit(X_train, y_train_log)

"""RFE dropped for the same reason as sfs computationaly both these model are to expensive and take a long time. while K-best give similar or better result.

## Gradient Boosting, Random Forest & Linear Regressor
"""

def create_regr_ppln(est, preprocessor):
    regr_pipe = Pipeline(
        steps=[
            ("pp", preprocessor),
            ("regr", est)
        ]
    )
    return regr_pipe

"""### Model Fitting"""

gbr = create_regr_ppln(TransformedTargetRegressor(
    regressor=GradientBoostingRegressor(n_estimators=50
                                        , max_depth=4
                                        , subsample=0.8
                                        , learning_rate=0.05
                                        ,random_state=42),
    func=np.log1p, inverse_func=np.expm1), preprocessor)

rfr = create_regr_ppln(TransformedTargetRegressor(
    regressor=RandomForestRegressor(n_estimators=50,
                                    max_features='sqrt',
                                    random_state=42),
    func=np.log1p, inverse_func=np.expm1), preprocessor)

lr = create_regr_ppln(TransformedTargetRegressor(
    regressor=LinearRegression(),
    func=np.log1p, inverse_func=np.expm1), preprocessor)

gbr.fit(X_train, y_train)
rfr.fit(X_train, y_train)
lr.fit(X_train, y_train)

gbr_preds_test = gbr.predict(X_test)
gbr_preds_train = gbr.predict(X_train)
rfr_preds_test = rfr.predict(X_test)
rfr_preds_train = rfr.predict(X_train)
lr_preds_test = lr.predict(X_test)
lr_preds_train = lr.predict(X_train)

gbr_mae_test = mean_absolute_error(y_test, gbr_preds_test)
gbr_mae_train = mean_absolute_error(y_train, gbr_preds_train)

print(f"GBR Test MAE:  {gbr_mae_test:,.2f}")
print(f"GBR Train MAE: {gbr_mae_train:,.2f}")

rfr_mae_test = mean_absolute_error(y_test, rfr_preds_test)
rfr_mae_train = mean_absolute_error(y_train, rfr_preds_train)

print(f"RFR Test MAE:  {rfr_mae_test:,.2f}")
print(f"RFR Train MAE: {rfr_mae_train:,.2f}")

lr_mae_test = mean_absolute_error(y_test, lr_preds_test)
lr_mae_train = mean_absolute_error(y_train, lr_preds_train)

print(f"LR Test MAE:   {lr_mae_test:,.2f}")
print(f"LR Train MAE:  {lr_mae_train:,.2f}")

gbr_r2_test = gbr.score(X_test, y_test)
gbr_r2_train = gbr.score(X_train, y_train)

print(f"GBR Test R2:  {gbr_r2_test:.4f}")
print(f"GBR Train R2: {gbr_r2_train:.4f}")

rfr_r2_test = rfr.score(X_test, y_test)
rfr_r2_train = rfr.score(X_train, y_train)

print(f"RFR Test R2:  {rfr_r2_test:.4f}")
print(f"RFR Train R2: {rfr_r2_train:.4f}")

lr_r2_test = lr.score(X_test, y_test)
lr_r2_train = lr.score(X_train, y_train)

print(f"LR Test R2:   {lr_r2_test:.4f}")
print(f"LR Train R2:  {lr_r2_train:.4f}")

"""## Ensembling

### Model Fitting
"""

my_models = [ gbr, rfr] # selected models to chose from

model_results_list = []
for my_model in my_models:
    eval_results = cross_validate(
        my_model, X_train, y_train, cv=3,
        scoring='neg_mean_absolute_error',
        return_train_score=True, n_jobs=-1)
    model_results_list.append(
        (-eval_results['test_score'].mean(), eval_results['test_score'].std(),
         -eval_results['train_score'].mean(), eval_results['train_score'].std()))

model_results = pd.DataFrame(
    model_results_list,
    columns=['test_mae_mean', 'test_mae_std', 'train_mae_mean', 'train_mae_std'],
    index=['gbr', 'rfr'])
display(model_results)

"""### Ensembling"""

ensemble = VotingRegressor(
    estimators=[
        ('gb', gbr),
        ('rf', rfr)
    ],
    weights=[0.5, 0.7],
    n_jobs=-1)

print("Running MAE cross-validation on full dataset...")
mae_results = cross_val_score(
    ensemble, X_train, y_train, cv=3,
    scoring='neg_mean_absolute_error', n_jobs=-1)
print(f"Voting Ensemble CV MAE: {-mae_results.mean():.2f} (+/- {mae_results.std() * 2:.2f})")

print("Running R2 cross-validation on full dataset...")
r2_results = cross_val_score(
    ensemble, X_train, y_train, cv=3,
    scoring='r2', n_jobs=-1)
print(f"Voting Ensemble CV R2: {r2_results.mean():.4f} (+/- {r2_results.std() * 2:.4f})")

ensemble.fit(X_train, y_train)

# The ensemble achieves a strong Test R2 (~0.90), outperforming the GBR and
# showing robust generalization compared to the slightly overfit RFR.
print("Train R2:", ensemble.score(X_train, y_train))
print("Test R2:", ensemble.score(X_test, y_test))

"""### Inspection"""

# quickly adapted from the sklearn documentation
# https://scikit-learn.org/stable/auto_examples/ensemble/plot_voting_regressor.html
xt = X.head(20)
yt = y.head(20)
# Predict using the fitted individual models and the ensemble model
pred_gbr = gbr.predict(xt)
pred_rfr = rfr.predict(xt)
# pred_lr = lr.predict(xt)
pred_ens = ensemble.predict(xt)

fig, ax = plt.subplots(figsize=(12, 6))

# Using a log scale for the y-axis to handle the price range better
ax.plot(pred_gbr, "gd:", alpha=0.4, label="GBR")
ax.plot(pred_rfr, "b^-.", alpha=0.4, label="RFR")
ax.plot(pred_ens, "r*-", alpha=0.7, ms=8, label="Ensemble")
ax.plot(yt.values, "ko", alpha=0.3, ms=4, label="True Data")

ax.set_yscale('log')
ax.tick_params(axis="x", which="both", bottom=False, labelbottom=False)
ax.set_ylabel("Price (Log Scale)")
ax.set_xlabel("Samples (First 20)")
ax.legend(loc="upper right", bbox_to_anchor=(1.15, 1))
ax.set_title("Comparison of Regressor Predictions (Log Scale)")
plt.tight_layout()
plt.show()

"""### Permutation Importance"""

perm_importance = permutation_importance(
    ensemble, X_test, y_test, n_repeats=30, random_state=0, scoring='neg_mean_absolute_error')

perm_importance_df = pd.DataFrame(
    dict(feature=X_test.columns,
        pi_mean=perm_importance['importances_mean'],
        pi_std=perm_importance['importances_std']))

perm_importance_df

perm_importance_df_sorted = perm_importance_df.sort_values(by='pi_mean', ascending=True)

# Visualisation Option 1: Error Bars
fig, ax = plt.subplots(figsize=(8, 6))
ax.errorbar(
    perm_importance_df_sorted['pi_mean'],
    perm_importance_df_sorted['feature'],
    xerr=perm_importance_df_sorted['pi_std'],
    fmt='o', color='black',
    ecolor='lightgray', elinewidth=5, capsize=0)
ax.set_ylabel('Feature')
ax.set_xlabel('Permutation Importance Mean');

"""### SHAP Explainer and Local Explanations"""

X_train_pp = gbr.named_steps["pp"].transform(X_train)
X_test_pp  = gbr.named_steps["pp"].transform(X_test)
gbr_model = gbr.named_steps["regr"]
rf_model  = rfr.named_steps["regr"]

# SHAP TreeExplainer needs the underlying tree model, not the meta-regressor wrapper.
explainer_gbr = shap.TreeExplainer(gbr.named_steps['regr'].regressor_,feature_perturbation="tree_path_dependent")
explainer_rf  = shap.TreeExplainer(rfr.named_steps['regr'].regressor_, feature_perturbation="tree_path_dependent")

# creates a TreeExplainer by default (based on the model passed)
explainer_gbr
explainer_rf

# Use a smaller sample to speed up SHAP calculation
shap_sample = shap.sample(X_test_pp, 20, random_state=42)

# Using the specific tree-path to speed up calculation
shap_gbr = explainer_gbr(shap_sample, check_additivity=False).values

shap_rf  = explainer_rf(shap_sample, check_additivity=False).values

# Ensemble SHAP = average VotingRegressor averages predictions
shap_ensemble = (shap_gbr + shap_rf) / 2

ensemble_expected_value = (explainer_gbr.expected_value + explainer_rf.expected_value) / 2
shap_ensemble_explanation = shap.Explanation(values=shap_ensemble, base_values=ensemble_expected_value, data=shap_sample)
shap.plots.beeswarm(shap_ensemble_explanation)

shap.plots.waterfall(shap_ensemble_explanation[0], max_display=10)

shap.initjs()
shap.plots.force(shap_ensemble_explanation[0])

# a global explanation: mean absolute SHAP as feature importance
shap.summary_plot(shap_ensemble,X_test_pp, plot_type="bar", max_display=10)

# compare the above to our usual model-specific feature importance
plt.figure(figsize=(10, 6))
sns.barplot(x='pi_mean', y='feature', data=perm_importance_df_sorted)
plt.title('Permutation Importance of Features (Mean Absolute Error)')
plt.xlabel('Permutation Importance (Mean)')
plt.ylabel('Feature')
plt.show()

"""#### Visualising Predictions as a Function of a Feature"""

plt.figure(figsize=(15, 6))
sns.scatterplot(x=X_test['fuel_type'], y=y_test, alpha=0.5)
ax = sns.scatterplot(x=X_test['fuel_type'], y=rfr.predict(X_test), alpha=0.5);

"""### Partial Dependency Plot (PDP)"""

PartialDependenceDisplay.from_estimator(
    ensemble,
    X_test.head(100),
    features=['mileage_per_year'],
    kind='both',
    pd_line_kw={'color': 'red'});

X_test['mileage_per_year'].head(10).min(), X_test['mileage_per_year'].head(10).max()

PartialDependenceDisplay.from_estimator(
    ensemble,
    X_test,
    features=['mileage_per_year'],
    kind='average');

fig, ax = plt.subplots(figsize=(8,6), constrained_layout=True)
PartialDependenceDisplay.from_estimator(
    ensemble,
    X_test.head(100),
    features=['mileage_per_year', 'vehicle_age'],
    kind='both',
    subsample=100,
    grid_resolution=30,
    n_jobs=-1,
    random_state=0,
    ax=ax,
    n_cols=2,
    pd_line_kw={'color': 'red'});

fig, ax = plt.subplots(figsize=(8,6), constrained_layout=True)
PartialDependenceDisplay.from_estimator(
    ensemble, X_test.head(100), features=['mileage_per_year', 'vehicle_age'],
    kind='both',
    centered=True,
    subsample=100,
    grid_resolution=30,
    n_jobs=2,
    random_state=0,
    ax=ax,
    n_cols=2,
    pd_line_kw={'color': 'red'});

fig, ax = plt.subplots(figsize=(8,6), constrained_layout=True)
PartialDependenceDisplay.from_estimator(
    ensemble,
    X_test.head(100),
    features=['mileage_per_year', 'vehicle_age'],
    kind='average',
    subsample=1000,
    grid_resolution=30,
    n_jobs=2,
    random_state=0,
    ax=ax,
    n_cols=2);

"""# Part 2

## Dimensionality Reduction (Linear)

Create sampled data for dimensionality reduction to avoid crashes with large dataset
"""

X_full = preprocessor.fit_transform(X, y)

sample_size = 1000
np.random.seed(42) # Set seed for reproducibility
indices = np.random.choice(len(X_full), sample_size, replace=False)
X_scaled_sample = X_full.iloc[indices]
y_sample = y.iloc[indices]

print(f"Created sampled data with {len(X_scaled_sample)} observations.")

# apply PCA function..
pca = PCA(n_components=2,  random_state=42)
X_pca = pca.fit_transform(X_scaled_sample)

df_pca = X_pca.copy()
df_pca.columns = ['PC1', 'PC2']
df_pca['price'] = y_sample

print('df_pca head before plotting:')
display(df_pca.head())

price_bins = pd.qcut(y_sample, q=5, labels=['Very Low','Low','Mid','High','Very High'])

fig, ax = plt.subplots(figsize=(7, 5))
scatter = sns.scatterplot(
    ax=ax,
    x=df_pca['PC1'], y=df_pca['PC2'],
    hue=price_bins,
    palette='viridis',
    alpha=0.7,
    edgecolor='w')
plt.title("PCA on Price data (Linear Projection)")
# cbar = plt.colorbar(scatter.collections[0], ax=ax, label='Price')
plt.show()

"""###2 components (Elbow point)"""

X_pca_4d = X_pca

# Pair plot for PCA components
df_pca_4d = X_pca_4d.copy()
df_pca_4d.columns = ['PC1', 'PC2']
df_pca_4d['price'] = y_sample

sns.pairplot(df_pca_4d, hue='price', palette='viridis')
plt.suptitle('Pair Plot for First 2 PCA Components', y=1.02)
plt.show()

"""### Nonlinear Dimensionality Reduction (MDS)"""

mds = MDS(n_components=3, random_state=42)
X_mds = mds.fit_transform(X_scaled_sample)

# plot MDS results
price_bins = pd.qcut(y_sample, q=5, labels=['Very Low','Low','Mid','High','Very High'])

plt.figure(figsize=(5, 5))
scatter_plot = sns.scatterplot(
    x=X_mds[:, 0],
    y=X_mds[:, 1],
    hue=price_bins,
    palette='viridis',
    s=20,
    alpha=0.7
)
plt.title("MDS on car dataset (global distances)")
# plt.colorbar(scatter_plot.collections[0], label='Price') # Removed explicit colorbar
plt.show()

"""### Isomap"""

# Apply Isomap
isomap = Isomap(n_components=2, n_neighbors=10)
X_iso = isomap.fit_transform(X_scaled_sample)

# Plot Isomap results
price_bins = pd.qcut(y_sample, q=5, labels=['Very Low','Low','Mid','High','Very High'])

plt.figure(figsize=(7, 5))
scatter_plot = sns.scatterplot(
    x=X_iso.iloc[:, 0],
    y=X_iso.iloc[:, 1],
    hue=price_bins,
    palette='viridis',
    s=20,
    alpha=0.7
)
plt.title("Isomap on car dataset (Geodesic Distances)")
# plt.colorbar(scatter_plot.collections[0], label='Price') # Removed explicit colorbar
plt.show()

"""### t-SNE"""

# Apply t-SNE
tsne = TSNE(n_components=2, perplexity=80, random_state=42)
X_tsne = tsne.fit_transform(X_scaled_sample)

# plotting t-SNE results
price_bins = pd.qcut(y_sample, q=5, labels=['Very Low','Low','Mid','High','Very High'])

plt.figure(figsize=(6, 5))
scatter_plot = sns.scatterplot(
    x=X_tsne.iloc[:,0],
    y=X_tsne.iloc[:,1],
    hue=price_bins,
    palette='viridis',
    s=10,
    alpha=0.7)

plt.title("t-SNE on car dataset (Local Neighbors) - better or worse?")
# plt.colorbar(scatter_plot.collections[0], label='Price') # Removed explicit colorbar
plt.show()

"""### Side-by-side comparison"""

# Plot all methods
fig, ax = plt.subplots(1, 4, figsize=(20, 5))
titles = ['PCA', 'MDS', 'Isomap', 't-SNE']
embeddings = [X_pca, X_mds, X_iso, X_tsne]

# Ensure all embeddings are NumPy arrays for consistent slicing
embeddings_np = []
for embed in embeddings:
    if isinstance(embed, pd.DataFrame):
        embeddings_np.append(embed.to_numpy())
    else:
        embeddings_np.append(embed)
# Define price_bins here to ensure it's available for this cell
price_bins = pd.qcut(y_sample, q=5, labels=['Very Low','Low','Mid','High','Very High'])

for i in range(4):
    # Use price_bins for consistent coloring across all plots
    ax[i].scatter(embeddings_np[i][:, 0], embeddings_np[i][:, 1], c=price_bins.cat.codes, cmap='viridis', s=20)
    ax[i].set_title(titles[i])
    ax[i].axis('off')  # Hide axes for clarity
plt.suptitle("Dimensionality reduction face-off on Car dataset - t-SNE is better")
plt.show()

"""## Generalized Linear Models

### Polynomial Regression
"""

X_original  = X_scaled_sample['mileage_per_year'].values
y_original = y_sample.values

"""Log transform target and normalize mileage_per_year for stability due to large values"""

y_log = np.log1p(y_original)
X_p = (X_original - X_original.mean()) / X_original.std()
models_poly = {}

for degree in [1, 2, 3, 5]:
    X_poly_features = np.column_stack([X_p**i for i in range(1, degree+1)])
    X_poly_sm = sm.add_constant(X_poly_features)

    glm_poly = sm.GLM(y_log, X_poly_sm, family=sm.families.Gaussian(link=sm.families.links.Identity()))
    results_poly = glm_poly.fit(disp=0)

    models_poly[degree] = results_poly
    print(f"Degree {degree} model fitted")

"""### Visualization"""

X_plot = np.linspace(np.percentile(X_original, 1), np.percentile(X_original, 99), 200)
# normalize again
X_plot_scaled = (X_plot - X_original.mean()) / X_original.std()
# scatter plot
plt.scatter(X_original, y_original, alpha=0.5, s=30, color='gray', label="Class Data points")
for degree, model in models_poly.items():
    X_test_features = np.column_stack([X_plot_scaled**i for i in range(1, degree+1)])
    X_test_sm = sm.add_constant(X_test_features)
    y_pred_log = model.predict(X_test_sm)
    y_pred = np.expm1(y_pred_log)  # Inverse log transform
    plt.plot(X_plot, y_pred, label=f"Degree {degree}")
plt.legend()
plt.xlabel("Mileage_per_year")
plt.ylabel("Price")
plt.title("Polynomial Regression on Car Dataset (Sampled Data)")
plt.show()

"""## Clustering (K-mean)

Since k-means is unsupervised we will have to apply different set of transformers to prevent data leakage
"""

preprocessor_cluster = ColumnTransformer([
    ('scaler', StandardScaler(), num_feat),
    ('onehot_low', OneHotEncoder(sparse_output=False, handle_unknown='infrequent_if_exist', drop='if_binary'), low_card_cat_feat),
    ('onehot_high', OneHotEncoder(sparse_output=False, handle_unknown='ignore', drop='if_binary'), high_card_cat_feat),
    ('binary', OneHotEncoder(sparse_output=False, handle_unknown='ignore', drop='if_binary'), binary_cat_feat)
])

""" ### K-means clustering using 'sklearn library'"""

X_train_cluster_preprocessed = preprocessor_cluster.fit_transform(X_train)
# get col names
feature_names = preprocessor_cluster.get_feature_names_out()
# Converting the scaled data back to a DataFrame, keeping the original index
X_scaled_df = pd.DataFrame(X_train_cluster_preprocessed, columns=feature_names, index=X_train.index)
# applying K-Means with 3 clusters
kmeans = KMeans(n_clusters=3, random_state=42, n_init='auto')

# Fit and predict from the standardized data
labels_kmeans = kmeans.fit_predict(X_scaled_df)
# Perform PCA for visualization on the preprocessed data used for clustering
pca_for_clusters = PCA(n_components=2, random_state=42)
X_pca_clusters = pca_for_clusters.fit_transform(X_scaled_df)
# X_pca_clusters is already a DataFrame due to set_config(transform_output='pandas')

df_plot_clusters = X_pca_clusters.copy()
df_plot_clusters.columns = ['PC1', 'PC2']
df_plot_clusters['Cluster K-Means'] = labels_kmeans
# Add price for potential hue if desired, aligning with the original y_train index
df_plot_clusters['price'] = y_train

df_plot_clusters.groupby('Cluster K-Means')['price'].describe()

"""### K-mean Visualization"""

# Plotting the clusters using PCA for dimensionality reduction
plt.figure(figsize=(8, 6))
sns.scatterplot(x='PC1', y='PC2', hue='Cluster K-Means', data=df_plot_clusters, palette='viridis', s=100)
plt.title("K-Means Clustering (k=3) visualized with PCA")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.show()

"""### Optimal k (Elbow method)"""

# Calculating inertia for different values of k
inertia = []
K = range(1, 11)
for k in K:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(X_scaled_df)
    print(f"fitted K{k}")
    inertia.append(kmeans.inertia_)

"""### Elbow method visualization

"""

plt.figure(figsize=(10, 6))
plt.plot(K, inertia, marker='o', linestyle='-')
plt.xlabel('Number of clusters (k)')
plt.ylabel('Inertia')
plt.title('Elbow Method For Optimal k')
plt.xticks(K)
plt.grid(True)
plt.show()

"""### Knee locater"""

kl = KneeLocator(K, inertia, curve='convex', direction='decreasing')
optimal_k = kl.elbow
print(f"The optimal number of clusters is: {optimal_k}")

"""## DBSCAN Clustering

use sample to prevent system crash
"""

dbscan = DBSCAN(eps=3, min_samples=6)
labels_dbscan = dbscan.fit_predict(X_scaled_sample)

"""use pca for visualization"""

pca_for_dbscan_clusters = PCA(n_components=2, random_state=42)
X_pca_dbscan_clusters = pca_for_dbscan_clusters.fit_transform(X_scaled_sample)
df_plot_dbscan_clusters = X_pca_dbscan_clusters.copy()
df_plot_dbscan_clusters.columns = ['PC1', 'PC2']
df_plot_dbscan_clusters['Cluster DBSCAN'] = labels_dbscan

"""visualization"""

plt.figure(figsize=(10, 8))
sns.scatterplot(x='PC1', y='PC2', hue='Cluster DBSCAN', data=df_plot_dbscan_clusters, palette='viridis', s=50, alpha=0.7)
plt.title("DBSCAN clustering visualized with PCA")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.show()

display(y_sample.groupby(labels_dbscan).describe())